const http=require('node:http'); const fs=require('node:fs'); const path=require('node:path'); const crypto=require('node:crypto');
const {read}=require('./store'); const {decide,policy}=require('./policy'); const {buildDailyReport}=require('./reports');
const city=require('../config/city.json'); const connectors=require('../connectors/catalog.json'); const root=path.resolve(__dirname,'..');
const port=Number(process.env.PORT||8787); const host=process.env.HOST||'127.0.0.1';
function json(res,status,body){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body));}
function auth(req){const expected=process.env.MACS_COMMAND_TOKEN; if(!expected) return process.env.NODE_ENV!=='production'; const got=(req.headers.authorization||'').replace(/^Bearer /,''); return got.length===expected.length&&crypto.timingSafeEqual(Buffer.from(got),Buffer.from(expected));}
function serve(res,file,type){const p=path.join(root,'public',file);res.writeHead(200,{'content-type':type});fs.createReadStream(p).pipe(res);}
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local'); if(url.pathname==='/health/live') return json(res,200,{ok:true,service:'macs-command-city'}); if(url.pathname==='/health/ready') return json(res,200,{ok:true,configured:connectors.connectors.filter(x=>x.status==='not-configured').map(x=>x.id),production:false}); if(url.pathname==='/'||url.pathname==='/index.html') return serve(res,'index.html','text/html; charset=utf-8'); if(url.pathname==='/styles.css') return serve(res,'styles.css','text/css'); if(url.pathname==='/app.js') return serve(res,'app.js','text/javascript'); if(url.pathname.startsWith('/api/')&&!auth(req)) return json(res,401,{error:'private-command-center'}); if(url.pathname==='/api/overview') return json(res,200,{city,connectors,policy,clients:read('clients'),content:read('content'),tasks:read('tasks'),crypto:read('crypto')}); if(url.pathname==='/api/report/daily') return json(res,200,buildDailyReport()); if(url.pathname==='/api/policy'&&req.method==='POST'){let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{const x=JSON.parse(b||'{}');json(res,200,decide(x.action,{approved:x.approved===true}));}catch{json(res,400,{error:'invalid-json'});}});return;} json(res,404,{error:'not-found'});});
if(require.main===module) server.listen(port,host,()=>console.log(`MACS Command City on http://${host}:${port}`)); module.exports=server;
